/**
 * @module
 *
 * Internal types shared between the Glue runtime and the CLI/backend.
 *
 * This module contains the core type definitions used for event registration,
 * trigger configuration, and account injection throughout the Glue system.
 * These types ensure consistency between the runtime library and the backend
 * services that process and execute the registered triggers. These types should
 * not be needed by users creating Glues, its only for internal (to Glue) use.
 * @internal
 */

import { z } from "zod";

export interface TriggerEvent {
  /** The event source type (e.g., "github", "stripe", "webhook") */
  type: string;
  /** The unique label identifying the specific trigger registration.
   * Typically these are auto-generated by Glue to be incrementing numbers
   * but users can override them. */
  label: string;
  /** The event-specific data payload, structure varies by event type. */
  data?: unknown;
}

export const TriggerEvent: z.ZodType<TriggerEvent> = z.object({
  type: z.string(),
  label: z.string(),
  data: z.unknown(),
});

export interface TriggerRegistration {
  /** The event source type this trigger is registered for */
  type: string;
  /** A unique label to identify this specific trigger */
  label: string;
  /** Event source specific configuration (varies by type) */
  config?: unknown;
}

export const TriggerRegistration: z.ZodType<TriggerRegistration> = z.object({
  type: z.string(),
  label: z.string(),
  config: z.object({}).passthrough().optional(),
});

export interface AccountInjectionRegistration {
  /** The service type this account is for (e.g., "github", "stripe") */
  type: string;
  /** A unique label to identify this specific account injection */
  label: string;
  /** Service-specific account configuration (varies by type) */
  config?: unknown;
}

export const AccountInjectionRegistration: z.ZodType<AccountInjectionRegistration> = z
  .object({
    type: z.string(),
    label: z.string(),
    config: z.object({}).passthrough().optional(),
  });

/**
 * Container for all registrations in a Glue application. This is the type that
 * the runtime serves on the `/__glue__/getRegistrations` to the backend.
 */
export interface Registrations {
  /** All event trigger registrations in the application */
  triggers: TriggerRegistration[];
  /** All account injection registrations in the application */
  accountInjections: AccountInjectionRegistration[];
}

export const Registrations: z.ZodType<Registrations> = z.object({
  triggers: z.array(TriggerRegistration),
  accountInjections: z.array(AccountInjectionRegistration),
  // TODO secretInjections
});

export type { GithubConfig } from "./integrations/github/runtime.ts";
export type { GoogleAccountInjectionConfig } from "./integrations/google/runtime.ts";
export type { GmailConfig } from "./integrations/gmail/runtime.ts";
export type { WebhookConfig } from "./integrations/webhook/runtime.ts";
export type { CronConfig } from "./integrations/cron/runtime.ts";
export type { StreakAccountInjectionConfig, StreakConfig } from "./integrations/streak/runtime.ts";
export type { StripeConfig } from "./integrations/stripe/runtime.ts";
export type { IntercomConfig } from "./integrations/intercom/runtime.ts";
